### ISSUE TITLE
question about example-code

### ISSUE THREAD

**Issue by vdogmcgee** [SAIIL/CVS_challenge_code#3]
in the model.py, out Example as follow :
    --------
    >>> predictions = my_model(model_inputs=model_inputs)
    >>> print(predictions["overall_outputs"])
    [[0.2, 0.56, 0.75], [0.57, 0.75, 0.75], [0.78, 0.9, 0.9]]

so each list of the overall_outputs , for example the overall_outputs [0] = [0.2, 0.56, 0.75] , does it means that :
for cvs1, the probability of "label=1" is 0.20 , and  the probability of "label=0" is 0.80 ?  
for cvs2, the probability of "label=1" is 0.56 , and  the probability of "label=0" is 0.44 ?  
for cvs1, the probability of "label=1" is 0.75 , and  the probability of "label=0" is 0.25 ?

**Comment by DpkApt** [comment]
Hi, could you please link the relevant file. Also could you be please clarify what you mean by cvs1, cv2,... and label=0

**Comment by vdogmcgee** [comment]
https://github.com/SAIIL/CVS_challenge_code/blob/main/submission/example-algorithm/resources/model.py , line37 
my cvs1, cvs2, cvs3 means C1, C2, C3
 I wonder know  if the [0.2, 0.56, 0.75] means that : 
 for C1 , 0.2    means C1 is most likely not completed
 for C3 , 0.75  means C3 is most likely completed

**Comment by DpkApt** [comment]
Hey, You're exactly right. Please refer to the docstring for more details on this function. Detailed instructions for submission will also be provided soon.
